#! /usr/bin/env python

from statemanager.server import serve
from os import getcwd
from sys import stderr
from subprocess import run

import logging
logging.basicConfig(level=logging.DEBUG)

cwd = getcwd()
socketpath = cwd + '/test/test.sock'
socketowner = None
socketgroup = None
socketperms = 0o600

basedirs = {
    f'{cwd}/test/state': {
        'hashalgos': [
            'sha256-base64url',
        ],
    },
}

run(['mkdir', '-p', '--', f'{cwd}/test/state'])

try:
    serve(basedirs, socketpath, socketowner, socketgroup, socketperms)
except KeyboardInterrupt:
    stderr.write('\nQuitting due to keyboard interrupt.\n')
